apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: traffic-simulator
spec:
  selector:
    app: loki-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
