apiVersion: v1
kind: Service
metadata:
  name: opentelemetry
  namespace: traffic-simulator
spec:
  selector:
    app: opentelemetry
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
