apiVersion: v1
kind: Service
metadata:
  name: template-service
  namespace: traffic-simulator
spec:
  selector:
    app: template-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
